name: Deploy Pipelines - PROD

on:
  workflow_dispatch:
  push:
    branches:
      - EC-404-devops-decommissioning

jobs:
  deploy_on_prod:
    uses: ./.github/workflows/deploy-pipelines.yaml
    name: Deploy on PROD
    secrets: inherit
    with:
      environment: 'prod'
      resource_group_name: 'io-p-cgn-be-rg'
      app_name: 'io-p-cgn-merchant-fn'
      use_staging_slot: true
      use_private_agent: false
      health_check_path: '/api/v1/merchant/cgn/info'